# fly.toml app configuration file generated for course-theclimatethinker on 2023-04-25T16:59:41+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "GoHealthy"
primary_region = "sin"

[deploy]
  release_command = "sh /code/start.sh"

[env]
  PORT = "8000"

#[[mounts]]
  #source = "GoHealthy_volume"
  #destination = "/code/assets"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

#[[statics]]
  #guest_path = "/code/assets/static"
  #url_prefix = "/static/"
