"""
Django settings for GoHealthy project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ
import django_heroku
env = environ.Env()
# reading .env file
environ.Env.read_env()

from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = env.str("INSTALLED_APPS").split("', '")


CRONJOBS = [
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteOTP'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteResetLink'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.bookExpireAlert'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.changeBedNo'),
    ('*/5 * * * *', 'Go_Healthy_App.scheduletasks.tasks.expireBooking'),
    ('* */3 * * *', 'Go_Healthy_App.scheduletasks.tasks.multipleBookingWarning'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteExpireBooking'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteRealese'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteNonVerifyUser'),
]

BACKGROUND_TASK_RUN_ASYNC = True

GEOPOSITION_GOOGLE_MAPS_API_KEY = env("GEOPOSITION_GOOGLE_MAPS_API_KEY")
FAST2SMAS_API_KEY = env("FAST2SMAS_API_KEY")

MIDDLEWARE = env.str("MIDDLEWARE").split("', '")

ROOT_URLCONF = 'GoHealthy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoHealthy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'Go_Healthy_App.Users'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000 #1 month in second

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#STATIC_ROOT = BASE_DIR/ 'static'
STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'static/media'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'


#For Mail Sending
ADMINS = [
    (env("USERNAME"), env("EMAIL_HOST_USER")), #send error to this mail
]
MANAGERS = ADMINS

EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")


ADMIN_URL = env('ADMIN_URL')

django_heroku.settings(locals())

