"""
Django settings for GoHealthy project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ
import django_heroku
from decouple import config
"""
env = environ.Env()
# reading .env file
environ.Env.read_env()
"""
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


SECRET_KEY = config("SECRET_KEY")

DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

#INSTALLED_APPS = env.str("INSTALLED_APPS").split("', '")
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Go_Healthy_App.apps.GoHealthyAppConfig',
    'background_task',
    'django_crontab',
    'embed_video',
    'django_filters',
    'django.forms',
    'crispy_forms',
    'template_forms',
    'geoposition',
    'django_dropbox_storage',
    'storages',
    'boto'
]

CRONJOBS = [
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteOTP'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteResetLink'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.bookExpireAlert'),
    ('*/1 * * * *', 'Go_Healthy_App.scheduletasks.tasks.changeBedNo'),
    ('*/5 * * * *', 'Go_Healthy_App.scheduletasks.tasks.expireBooking'),
    ('* */3 * * *', 'Go_Healthy_App.scheduletasks.tasks.multipleBookingWarning'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteExpireBooking'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteRealese'),
    ('* */24 * * *', 'Go_Healthy_App.scheduletasks.tasks.deleteNonVerifyUser'),
]

BACKGROUND_TASK_RUN_ASYNC = True

GEOPOSITION_GOOGLE_MAPS_API_KEY = config("GEOPOSITION_GOOGLE_MAPS_API_KEY")
FAST2SMAS_API_KEY = config("FAST2SMAS_API_KEY")

#MIDDLEWARE = env.str("MIDDLEWARE").split("', '")
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]


ROOT_URLCONF = 'GoHealthy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoHealthy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config("DATABASE_ENGINE"),
        'NAME': config("DATABASE_NAME"),
        'USER': config("DATABASE_USER"),
        'PASSWORD': config("DATABASE_PASSWORD"),
        'HOST': config("DATABASE_HOST"),
        'PORT': config("DATABASE_PORT"),
    }
}
DATABASE_URL=config("DATABASE_URL")
AUTH_USER_MODEL = 'Go_Healthy_App.Users'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000 #1 month in second

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
#DROPBOX_OAUTH2_TOKEN = config('DROPBOX_OAUTH2_TOKEN')
#DROPBOX_ROOT_FOLDER = '/'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SFTP_STORAGE_HOST = "https://www.dropbox.com"
SFTP_STORAGE_ROOT = "home/Apps/GoHealthy/static"
SFTP_STORAGE_INTERACTIVE = False

"""
STATIC_ROOT = BASE_DIR/ 'staticfiles'
STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR / 'static/media'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
"""


#For Mail Sending
ADMINS = [
    (config("USERNAME"), config("EMAIL_HOST_USER")), #send error to this mail
]
MANAGERS = ADMINS

EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_USE_TLS = True
EMAIL_PORT = int(config("EMAIL_PORT"))
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")


ADMIN_URL = config('ADMIN_URL')

django_heroku.settings(locals())