from unicodedata import name
import django_eventstream
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.sitemaps import views as sitemapviews
from .sitemaps import *
from . import views

app_name = 'Go_Healthy_App'


urlpatterns = [
    path('', views.Home, name='project-Home'),
    path('hospitals/', views.Hospitals, name='project-Hospital'),
    path('hospital/<id>/', views.hospitalPage, name='HospitalPage'),
    path('bedbook/<hospitalID>/',views.BedBook, name='bedbook'),
    path('patient-info/<id>/', views.BedBookView, name='BookStatus'),
    path('patient-info/pdf/<id>/', views.bedBookPDF, name="BookingPDF"),
    path('blood-donors/', views.Blood, name='project-Blood'),
    path('blood-banks/', views.BloodBankView, name='BloodBank'),
    path('blood-bank/<id>/', views.bloodBankPage, name='BloodBankPage'),
    path('doctors/', views.Doctors, name='project-Doctor'),
    path('blood-donation-camps/', views.bloodDonationCamp, name='BloodDonationCamps'),
    path('blood-donation-camp-registration/', views.bloodDonationCampRegistration, name='BloodDonationCampRegistration'),
    path('blood-donation-camp-edit/', views.bloodDonationCampEdit, name='BloodDonationCampEdit'),
    path('blood-donation-camp-cancel/', views.cancelBloodDonationCamp, name='CancelBloodDonationCamp'),
    path('set-blood-donation-camp-reminder/', views.setBloodDonationCampReminder, name='SetBloodDonationCampReminder'),
    path('blood-donation-camp/<id>/',views.bloodDonationCampDetail, name='BloodDonationCampDetail'),
    path('bmi/', views.BMIAnswer, name='BMI-Answer'),
    path('our-vision/', views.About, name='project-About'),
    path('contact/', views.ContactUsView, name='project-Contact'),
    path('ajax-contact/', views.AjaxContact, name='Ajaxcontact'),
    path('complaint/', views.ComplaintView, name='project-Complain'),
    path('age-check/', views.AgeCheck, name='AgeCheck'),
    path('registration-no-check/', views.registrationNoCheck, name='RegistrationNoCheck'),
    path('add-rating/', views.addRating, name='AddRating'),
    path('learn-firstaid/',views.firstaid, name='project-Firstaid'),
    path('firstaid-instructor-profile/', views.firstaidInstructorProfile, name='FirstAidInstructorProfile'),
    path('firstaid-instructor/<username>/', views.firstaidInstructor, name='FirstAidInstructor'),
    path('firstaid-photo-courses/', views.firstaid_photo, name='firstaid-Photos'),
    path('firstaid-video-courses/',views.firstaid_video, name='firstaid-Videos'),
    path('firstaid-photo-course/<id>/<slug>/', views.firstaid_photo_course, name='firstaid-Photo-course'),
    path('firstaid-video-course/<id>/<slug>/',views.firstaid_video_course, name='firstaid-Video-course'),
    path('emergency-number/', views.EmergencyNumber, name='Emergency'),
    path('register/', views.NormalRegistration, name='Register'),
    path('register/blood-donor/', views.RegisterDonor, name='Register-Donor'),
    path('register/doctor/', views.RegisterDoctor, name='Register-Doctor'),
    path('register/hospital/', views.hospitalRegistration, name='Register-Hospital'),
    path('register/hospital/<id>/', views.hospitalRegistrationPart_2, name='HospitalRegistrationPart_2'),
    path('hospital-add-bed/', views.addBed, name='AddBed'),
    path('recent-added-beds/', views.recentAddeBeds, name='RecentAddeBeds'),
    path('all-bed-remove-requests/', views.allBedRemoveRequests, name='AllBedRemoveRequests'),
    path('undo-bed-remove-requests/', views.undoBedRemove, name='UndoBedRemove'),
    path('hospital-remove-bed/', views.removeBed, name='RemoveBed'),
    path('all-added-beds/', views.allAddedBeds, name='AllAddedBeds'),
    path('get-rooms-by-hospital/', views.allAddedRooms, name='AllAddedRooms'),
    path('get-units-by-hospital/', views.allAddedUnits, name='AllAddedUnits'),
    path('get-buildings-by-hospital/', views.allAddedBuildings, name='AllAddedBuildings'),
    path('add-rooms/', views.addRoom, name='AddRoom'),
    path('delete-room/', views.deleteRoom, name='DeleteRoom'),
    path('edit-room/', views.editRoom, name='EditRoom'),
    path('add-units/', views.addUnit, name='AddUnit'),
    path('delete-unit/', views.deleteUnit, name='DeleteUnit'),
    path('edit-unit/', views.editUnit, name='EditUnit'),
    path('add-buildings/', views.addBuilding, name='AddBuilding'),
    path('delete-building/', views.deleteBuilding, name='DeleteBuilding'),
    path('edit-building/', views.editBuilding, name='EditBuilding'),
    path('register-hospital-submit/', views.registerHospitalSubmit, name='RegisterHospitalSubmit'),
    path('register/blood-bank/', views.bloodBankRegistration, name='Register-Blood-Bank'),
    path('register/blood-bank/<id>/', views.bloodBankRegistration_part2, name='BloodBankRegistration_part2'),
    path('register-blood-bank-submit/', views.registerBloodBankAddBlood, name='Register-Blood-Bank-submit'),
    path('send-otp-blood-donation/', views.OTPSendBloodDonationCampRegister, name='OTPSendBloodDonation'),
    path('verify-otp-blood-donation/', views.OTPVerifyBloodDonationCampRegister, name='OTPVerifyBloodDonation'),
    path('send-otp-blood-donation-camp-edit/', views.OTPSendBloodDonationCampEdit, name='OTPSendBloodDonationEdit'),
    path('verify-otp-blood-donation-camp-edit/', views.OTPVerifyBloodDonationCampEdit, name='OTPVerifyBloodDonationEdit'),
    path('get-registered-blood-donation-camps/', views.getRegisteredBloodDonoationCamps, name='GetRegisteredBloodDonoationCamps'),
    path('get-registered-blood-donation-camp-data/', views.getBloodDonationCampData, name='GetBloodDonationCampData'),
    path('send-otp-register/', views.OTPSendReg, name='OTPSendReg'),
    path('verify-otp-register/', views.OTPVerifyReg, name='OTPVerifyReg'),
    path('send-otp-blood-request/', views.OTPSendBloodRequest, name='OTPSendBloodRequest'),
    path('username-validation/', views.UsernameValid, name='username-validation'),
    path('email-validation/', views.EmailValid, name='email-validation'),
    path('my-profile/', views.UserProfile, name='Profile'),
    path('blood-bank-admin/', views.bloodBankAdminProfile, name='BloodBankAdminProfile'),
    path('update-blood/', views.updateBlood, name='UpdateBlood'),
    path('blood-certificates-search/', views.certificatesSearch, name='CertificatesSearch'),
    path('my-blood-donation-collection/', views.myBloodBankRecord, name='MyBloodBankRecord'),
    path('blood-certificate/<id>/', views.showBloodDonationCertificate, name='ShowBloodDonationCertificate'),
    path('generate-blood-certificate/', views.generateBloodCertificate, name='GenerateBloodCertificate'),
    path('hospital-admin/', views.HospitalAdmin, name="HospitalAdmin"),
    path('hospital-admin-admit-search/', views.admitSearch, name="AdmitSearch"),
    path('hospital-admin-refer-search/', views.referSearch, name="ReferSearch"),
    path('hospital-admin-referral-search/', views.referralPatientSearch, name="ReferralSearch"),
    path('hospital-admin-release-search/', views.pastPatientsSearch, name="PastPatientsSearch"),
    path('referral-patient-edit/', views.referralpatientEdit, name="ReferralpatientEdit"),
    path('my-profile/donor/', views.DonorProfile, name="DonorProfile"),
    path('my-profile/doctor/', views.DoctorProfile, name="DoctorProfile"),
    path('my-profile/normal-user/', views.NormalProfile, name="NormalProfile"),
    path('site-admin/', views.siteAdminProfile, name="SiteAdminProfile"),
    path('send-blood-request/', views.bloodRequest, name='SendBloodRequest'),
    path('blood-requests/', views.requestedBlood, name='RequestedBlood'),
    path('people-voice/', views.peopleVoice, name='PeopleVoice'),
    path('get-all-disease/', views.getAllDiseases, name='GetAllDiseases'),
    path('get-hospitals-by-name/', views.getHospitalsByName, name='GetAllHospitals'),
    path('submit-feedback/', views.feedbackSubmit, name='FeedbackSubmit'),
    path('fetch-beds-data/', views.fetchBedInfo, name='FetchBedInfo'),
    path('get-department-beds-availibility/', views.getDepartmentBedAvailabilityData, name='GetDepartmentBedAvailabilityData'),
    path('get-beds-info/', views.getBedData, name='GetBedData'),
    path('edit-bed/', views.editBedInfo, name='EditBedInfo'),
    path('get-department-beds/', views.getDepartmentBeds, name='GetDepartmentBeds'),
    path('reserve-book/', views.reserveBooking, name='ReserveBook'),
    path('get-booking-details/', views.getBookingDetails, name='GetBookingData'),
    path('status-update/', views.statusUpdate, name='StatusUpdate'),
    path('patient-edit/',views.PatientEdit, name='PatientEdit'),
    path('patient-update/',views.patientUpdate, name='PatientUpdate'),
    path('new-book/', views.NewBook, name='NewBook'),
    path('status-check/', views.StatusChecK, name='StatusCheck'),
    path('update-antivenom/', views.updateAntivenom, name='UpdateAntivenom'),
    path('update-oxygen/', views.updateOxygen, name="UpdateOxygen"),
    path('chat/', views.ChatView, name='Chat'),
    path('delete-chat/', views.DeleteChat, name='Delete-Chat'),
    path('total-chat/', views.TotalChat, name='Total-Chat'),
    path('count-visitor/', views.countVisitor, name='CountVisitor'),
    path('hospital-general-save-change/', views.hospitalgeneralEdit, name='HospitalGeneralEdit'),
    path('hospital-contact-edit/', views.HospitalContactEdit, name='HospitalContactEdit'),
    path('bloodbank-general-save-change/', views.bloodBankGeneralEdit, name='BloodBankGeneralEdit'),
    path('bloodbank-contact-edit/', views.BloodBankContactEdit, name='BloodBankContactEdit'),
    path('get-speciality/', views.LoadSpeciality, name='GetSpeciality'),
    path('get-address/', views.LoadAddressFromPin, name='LoadAddress'),
    path('get-address-gps/', views.getAddressFromCord, name='LoadAddressGPS'),
    path('get-district/', views.LoadDistrict, name='LoadDistrict'),
    path('get-hospitals-by-state/', views.getHospitalsByState, name='LoadHospitalsByState'),
    path('get-hospitals-by-cord/', views.getHospitalByCord, name='LoadHospitalsByCord'),
    path('get-blood-banks-by-state/', views.getBloodBanksByState, name='LoadBloodBanksByState'),
    path('get-city/', views.getCity, name='GetCity'),
    path('my-bookings/', views.MyBookings, name='MyBookings'),
    path('display-pic/', views.displayProfile, name='DisplayPic'),
    path('login/', views.LoginMain, name='LoginMain'),
    path('change-password/', views.PasswordChange, name='ChangePassword'),
    path('check-password/', views.Passwordcheck, name='CheckPassword'),
    path('reset-password/', views.ResetPasswordLink, name='ResetPassword'),
    path('reset-password/<code>/', views.ResetPassword, name='ResetPasswordDone'),
    path('edit-otp-send/', views.OTPSendEdit, name='Edit-Opt-Send'),
    path('edit-contact/', views.ContactUpdate, name='Edit-Contact'),
    path('hospital-edit-otp-send/', views.otpSendHospitalContactEdit, name='Hospital-Edit-Opt-Send'),
    path('bloodbank-edit-otp-send/', views.otpSendBloodBankContactEdit, name='BloodBank-Edit-Opt-Send'),
    path('hospital-image-change/', views.hospitalImageChange, name='HospitalImageChange'),
    path('edit-bloodgroup/', views.EditBloodGroup, name='Edit-BloodGroup'),
    path('profile-upgrade/', views.ProfileUpgrade, name='Profile-Upgrade'),
    path('data-and-statistics/', views.dataCenter, name='DataCenter'),
    path('logout/', views.Logout, name='Logout'),
    path('javascript-error/', views.noScriptView, name='noScript'),
    path('faq/', views.faq, name='FAQ'),
    path('blood-donor-eligibility/', views.donorEligibility, name="DonorEligibility"),
    path('terms-and-conditions/', views.termsConditions, name='TermsConditions'),
    path('column-graph-blood-donation-collection-data/', views.columnGraph_bloodDonatedandCollected, name="ColumnGraph_bloodDonatedandCollected"),
    path('column-graph-blood-request-donation-data/', views.columnGraph_bloodRequestedandDonated, name="ColumnGraph_bloodRequestedandDonated"),
    path('column-graph-blood-donation-camp-data/', views.columnGraph_bloodDonationCamps, name="ColumnGraph_bloodDonationCamps"),
    #path('hospital-oxygen/', views.Hospital_Oxygen_Level.as_view()),
    #path('hospital-oxygen/<int:pk>/', views.Hospital_Oxygen_Level_details.as_view()),
    
    path('events/live-notification/', include(django_eventstream.urls), { 'user_specific-channels': ['notification-{username}'] }),
    path('events/now-book/', include(django_eventstream.urls), { 'user_specific-channels': ['nowBook-{username}'] }),
    path('events/live-data/', include(django_eventstream.urls), { 'channels': ['liveData'] }),
    path('events/live-site-visitor/', include(django_eventstream.urls), { 'channels': ['liveSiteVisitor'] }),
    path('events/live-bed/', include(django_eventstream.urls), { 'channels': ['liveBed'] }),
    path('events/live-blood-status/', include(django_eventstream.urls), { 'channels': ['liveBloodStatus'] }),
    path('events/new-disease/', include(django_eventstream.urls), { 'channels': ['newDisease'] }),
    ]
urlpatterns = format_suffix_patterns(urlpatterns)
