# Generated by Django 3.1.4 on 2021-01-04 12:27

import Go_Healthy_App.validators
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed_No', models.CharField(max_length=5)),
                ('Flor', models.CharField(choices=[('Ground Flor', 'Ground Flor'), ('1st Flor', '1st Flor'), ('2nd Flor', '2nd Flor'), ('3rd Flor', '3rd Flor'), ('4th Flor', '4th Flor'), ('5th Flor', '5th Flor'), ('6th Flor', '6th Flor'), ('7th Flor', '7th Flor')], max_length=50)),
                ('Room', models.CharField(choices=[('General Ward', 'General Ward'), ('Women Ward', 'Women Ward'), ('Men Ward', 'Men Ward'), ('Child Ward', 'Child Ward'), ('ICU', 'ICU')], max_length=100)),
                ('Building', models.CharField(max_length=100)),
                ('Availability', models.CharField(choices=[('Available', 'Available'), ('Used', 'Used'), ('Book', 'Book')], default='Available', max_length=50)),
                ('Booking_Id', models.CharField(blank=True, max_length=10, null=True)),
                ('Book_Expire', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['Room', 'Bed_No', 'Building', 'Flor'],
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('Complain_Id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('District', models.CharField(max_length=100)),
                ('Subdivision', models.CharField(default='', max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Attachment', models.FileField(blank=True, help_text='If you have any document or proof regarding your complaint, then please attach it.', null=True, upload_to='')),
                ('Complain', models.TextField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Pending', max_length=50)),
                ('Reply', models.TextField(default='N/A')),
                ('Complaint_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Message', models.TextField()),
                ('Contact_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Registration_Number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Degree', models.CharField(default='MBBS', max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('I not prefered to say', 'I not prefered to say')], max_length=30)),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=20)),
                ('Special', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Union Teritory', 'Union Teritory'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('City', models.CharField(default='', max_length=200)),
                ('Subdivision', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Image', models.ImageField(upload_to='images/doctors/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['State', 'District', 'Subdivision', 'Special', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='Emargency_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office', models.CharField(max_length=500)),
                ('Title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=10)),
                ('Person', models.CharField(blank=True, max_length=500)),
                ('Person_Designation', models.CharField(blank=True, max_length=500)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Union Teritory', 'Union Teritory'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Subdivision', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=13)),
                ('Contact_1', models.CharField(blank=True, max_length=13)),
                ('Contact_2', models.CharField(blank=True, max_length=13)),
                ('Contact_3', models.CharField(blank=True, max_length=13)),
                ('Contact_4', models.CharField(blank=True, max_length=13)),
                ('Contact_5', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'ordering': ['State', 'District', 'Subdivision', 'Office'],
            },
        ),
        migrations.CreateModel(
            name='FirstaidPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Upload_Photo', models.ImageField(null=True, upload_to='first aid/images/')),
                ('Language', models.CharField(choices=[('Bengali', 'Bengali'), ('English', 'English'), ('Hindi', 'Hindi')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirstaidVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Video', models.FileField(upload_to='first aid/videos/', validators=[Go_Healthy_App.validators.validate_file_extension])),
                ('Language', models.CharField(choices=[('Bengali', 'Bengali'), ('English', 'English'), ('Hindi', 'Hindi')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Notice_and_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(choices=[('Notification', 'Notification'), ('News', 'News'), ('Event', 'Event')], max_length=100)),
                ('Name', models.CharField(max_length=500)),
                ('File', models.FileField(upload_to='document/Notice')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileOTP', models.CharField(default='000000', max_length=6)),
                ('EmailOTP', models.CharField(default='000000', max_length=6)),
                ('Mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Is_Verified', models.BooleanField(default=False)),
                ('Expire_Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('User_Type', models.CharField(choices=[('Normal', 'Normal'), ('Hospital', 'Hospital'), ('Doctor', 'Doctor'), ('Blood Donor', 'Blood Donor'), ('Admin', 'Admin'), ('Blood Donor & Doctor', 'Blood Donor & Doctor')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Expire_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Username', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('I not prefered to say', 'I not prefered to say')], max_length=30)),
                ('ID_Type', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('Voter Card', 'Voter Card'), ('PAN', 'PAN'), ("Doctor's Registration", "Doctor's Registration")], default='Aadhaar', max_length=100)),
                ('ID_Number', models.CharField(default='', max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Union Teritory', 'Union Teritory'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('City', models.CharField(default='', max_length=200)),
                ('Subdivision', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Image', models.ImageField(upload_to='images/normal users/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('Username', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Hospital_Id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('Type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=100)),
                ('Contact', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Union Teritory', 'Union Teritory'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('City', models.CharField(default='', max_length=200)),
                ('Subdivision', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Image', models.ImageField(upload_to='images/hospitals/')),
                ('Has_Antivenom', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('Location', models.URLField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('Username', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['State', 'District', 'Subdivision', 'Type', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Username',
            field=models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('From', models.ForeignKey(default='This User Account has been deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='From', to=settings.AUTH_USER_MODEL)),
                ('To', models.ForeignKey(default='This User Account has been deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='To', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Time'],
            },
        ),
        migrations.CreateModel(
            name='Blood_Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('I not prefered to say', 'I not prefered to say')], max_length=30)),
                ('Blood_Group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('Date_of_Birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('Contact', models.CharField(max_length=10)),
                ('ID_Type', models.CharField(choices=[('Aadhaar', 'Aadhaar'), ('Voter Card', 'Voter Card'), ('PAN', 'PAN'), ("Doctor's Registration", "Doctor's Registration")], max_length=100)),
                ('ID_Number', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Union Teritory', 'Union Teritory'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100)),
                ('City', models.CharField(default='', max_length=200)),
                ('Subdivision', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Image', models.ImageField(upload_to='images/blood donors/')),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('Username', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['State', 'District', 'Subdivision', 'Name', 'Blood_Group'],
            },
        ),
        migrations.CreateModel(
            name='BedRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.bedno')),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='bedno',
            name='Book_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedno',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.hospital'),
        ),
        migrations.CreateModel(
            name='Bed_Book',
            fields=[
                ('Booking_ID', models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Booked_By', models.CharField(choices=[('User', 'User'), ('Hospital Authority', 'Hospital Authority')], default='User', max_length=50)),
                ('Disease', models.CharField(blank=True, max_length=500, null=True)),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=10)),
                ('Alternative_Mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('Age', models.IntegerField(default=0)),
                ('Address', models.TextField()),
                ('Subdivision', models.CharField(default='', max_length=100)),
                ('State', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=6)),
                ('Gender', models.CharField(max_length=20)),
                ('Booking_Time', models.DateTimeField(auto_now_add=True)),
                ('Expire_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Admit_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Next_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Not Admit Still Now', 'Not Admit Still Now'), ('Admited', 'Admitted'), ('Released', 'Released'), ('Expired', 'Expired')], default='Not Admit Still Now', max_length=50)),
                ('Bed_No', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.bedno')),
                ('Hospital_Name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.hospital')),
                ('user', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Booking_Time'],
            },
        ),
    ]
