# Generated by Django 3.2 on 2022-08-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Go_Healthy_App', '0002_whatsappnumber_contact_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Go_Healthy_App.languages'),
        ),
    ]
