# Generated by Django 3.2 on 2022-08-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Go_Healthy_App', '0003_alter_complaint_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donar',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_district_blooddonors', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='blood_donar',
            name='Permanent_District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_district_blood_donors', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='blood_donar',
            name='Permanent_State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_state_blood_donors', related_query_name='permanent_state_blood_donor', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='blood_donar',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state_blooddonors', related_query_name='current_state_blooddonor', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_bloodbanks', related_query_name='state_bloodbank', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='blooddonationcamp',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='blooddonationcamp',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_blooddonationcamps', related_query_name='state_blooddonationcamp', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='blooddonationcollectionrecord',
            name='Blood_Bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.bloodbank'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.languages'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_complaints', related_query_name='state_complaint', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.degrees'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_district_doctors', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Permanent_District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_district_doctors', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Permanent_State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_state_doctors', related_query_name='permanent_state_doctor', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.specialities'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_states_doctors', related_query_name='current_states_doctor', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='emergency_number',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='emergency_number',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_emergencies', related_query_name='state_emergency', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='firstaidphotocourse',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.languages'),
        ),
        migrations.AlterField(
            model_name='firstaidvideocourse',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.languages'),
        ),
        migrations.AlterField(
            model_name='firstaidvideosubtitle',
            name='Subtitle_Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.languages'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_hospitals', related_query_name='state_hospital', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_district_normalusers', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='Permanent_District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_district_normalusers', to='Go_Healthy_App.districts'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='Permanent_State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_state_normalusers', related_query_name='permanent_state_normaluser', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state_normalusers', related_query_name='current_state_normaluser', to='Go_Healthy_App.states'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='Disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_patientsData', related_query_name='disease_patientData', to='Go_Healthy_App.disease'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bedbooks', related_query_name='user_bedbook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientshiftrecords',
            name='shift_form',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_shift_from_beds', related_query_name='patient_shift_from_bed', to='Go_Healthy_App.bedno'),
        ),
        migrations.AlterField(
            model_name='patientshiftrecords',
            name='shift_to',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_shift_to_beds', related_query_name='patient_shift_to_bed', to='Go_Healthy_App.bedno'),
        ),
        migrations.AlterField(
            model_name='peoplevoice',
            name='Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.languages'),
        ),
        migrations.AlterField(
            model_name='peoplevoice',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Go_Healthy_App.hospital'),
        ),
        migrations.AlterField(
            model_name='referredpatient',
            name='Bed',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_referredpatients', related_query_name='bed_referredpatient', to='Go_Healthy_App.bedno'),
        ),
        migrations.AlterField(
            model_name='somecommondisease',
            name='Concerned_Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_disease_departments', related_query_name='common_disease_department', to='Go_Healthy_App.hospitaldepartment'),
        ),
        migrations.AlterUniqueTogether(
            name='languages',
            unique_together={('Language', 'Local_Script')},
        ),
        migrations.AlterUniqueTogether(
            name='somecommondisease',
            unique_together={('Disease', 'Concerned_Department')},
        ),
    ]
