# Generated by Django 3.2 on 2023-05-05 16:29

import Go_Healthy_App.models
import Go_Healthy_App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_Healthy_App', '0005_alter_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Image',
            field=models.ImageField(upload_to=Go_Healthy_App.models.user_image_directory_path, validators=[Go_Healthy_App.validators.validate_image_type, Go_Healthy_App.validators.validate_file_size]),
        ),
    ]
