# Generated by Django 3.1.4 on 2021-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go_Healthy_App', '0006_complaint_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_book_allow',
            field=models.BooleanField(default=True),
        ),
    ]
